# Generated by Django 3.0.2 on 2020-05-13 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activity',
            new_name='Task',
        ),
    ]
